#!/bin/bash

admins=`config-get admins`

potential_admins=`echo "$admins" | tr -d ' ' | tr -d "'" | sed 's/,/ /g'`

if [ ! -f ".psql" ]; then
  juju-log "Waiting for a database"
  exit 0
fi

source .psql

export PGPASSWORD=$db_pass

if [ ! -z "$potential_admins" ]; then
  for i in ${potential_admins}; do
    juju-log "Attempting to add admin for $i"
    echo "UPDATE users SET admin=true WHERE username='$i'" | psql -h $db_host -U $db_user $db_dbdb
  done
fi

juju-log "Running upgrade-charm to handle the rest of configuration"

hooks/upgrade-charm
