#!/bin/bash

set -e

charm_dir=`pwd`

relation-set database="discourse"

juju-log "Sent things over the wire, wait for response."

database=`relation-get database`
user=`relation-get user`
pass=`relation-get password`
host=`relation-get host`
port=`relation-get port`

if [ -z "$user" ] || [ -z "$host" ]; then
  juju-log "Waiting for items on the wire"
  exit 0
fi

cat > /home/discourse/discourse/config/database.yml <<EOF
production:
  adapter: postgresql
  database: $database
  pool: 5
  timeout: 5000
  username: $user
  password: $pass
  port: $port
  host: $host
EOF

juju-log "Creating PostgreSQL Database"
PGPASSWORD=$pass createdb -U $user -h $host -o $user $database

cd /home/discourse/discourse

export RAILS_ENV="production"

juju-log "Raking databases and planting seeds!"
# The first Rake exits with a status of 1, even if it's successful. So, sorry.
set +e
sudo -u discourse -H bundle exec rake RAILS_ENV="production"
set -e
sudo -u discourse -H bundle exec rake db:migrate RAILS_ENV="production"
set +e
sudo -u discourse -H bundle exec rake RAILS_ENV="production"
set -e
sudo -u discourse -H bundle exec rake db:seed RAILS_ENV="production"


juju-log "Create assets"
sudo -u discourse -H bundle exec rake assets:clean RAILS_ENV="production"
sudo -u discourse -H bundle exec rake assets:precompile RAILS_ENV="production"

juju-log "Database set up"

open-port 80/tcp

if [ -f ".redis" ]; then
  start discourse
fi
