#!/bin/bash

set -e

repository=`config-get repository`
branch=`config-get branch`
branch=${branch:-master}
tag=`config-get release`

apt-get install -qy ruby1.9.3 git-core build-essential libxml2-dev \
  libxslt1-dev libpq-dev nginx redis-server postgresql-client-common \
  postgresql-client-9.1 sendmail

charm_dir=`pwd`

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

juju-log "Installing upstart scripts"
rsync -az contrib/upstart/*.conf /etc/init/

juju-log "Bundler ho!"
gem install bundler foreman

set +e
id discourse
user_exists=$?
set -e

if [ $user_exists -gt 0 ]; then
  juju-log "Create discourse user"
  adduser --disabled-password --gecos 'Discourse' discourse
fi

# Discourse should probably use gunicon. gunicorn is cool.
juju-log "Placing nginx configuration files"
rsync -az contrib/nginx/ /etc/nginx/sites-available/
rm -f /etc/nginx/sites-enabled/default

if [ ! -e /etc/nginx/sites-enabled/discourse ]; then
  ln -s ../sites-available/discourse /etc/nginx/sites-enabled/discourse
fi

service nginx restart

if [ -d "/home/discourse/discourse" ]; then
  juju-log "Updating repository..."
  cd /home/discourse/discourse
  sudo -u discourse -H git fetch
  sudo -u discourse -H git pull

  current_branch=$(git symbolic-ref -q HEAD)
  current_branch_name=${branch_name##refs/heads/}
  current_tag=$(git describe)

  if [ "$current_branch" != "$branch" ]; then
    juju-log "Moving current repository to $branch"
    if git for-each-ref --format "%(refname:short)" refs/heads/ | grep -Eq "^$branch$"; then
      juju-log "We already have this branch branched. Switch and pull"
      git checkout $branch
      git pull origin $branch
    else
      juju-log "Branching $branch"
      git checkout -b $branch origin/$branch
    fi
    touch $charm_dir/.migrate
  fi

  if [ "$current_tag" != "$tag" ]; then
    juju-log "Placing $branch branch at $tag"
    git reset --hard $tag
    touch $charm_dir/.migrate
  fi

  rm -f .foreman
else
  juju-log "Fetching source from $repository..."
  sudo -u discourse -H git clone $repository /home/discourse/discourse
  cd /home/discourse/discourse
  if [ "$branch" != "master" ]; then
    juju-log "Moving new repository to $branch"
    git checkout -b $branch origin/$branch
  fi

  if [ ! -z "$tag" ]; then
    juju-log "Placing $branch branch at $tag"
    git reset --hard $tag
  fi

  sudo -u discourse -H cp config/redis.yml.sample config/redis.yml
  mkdir -p ../.backup
fi

cp .procfile.sample .foreman

export RAILS_ENV="production"

juju-log "Bundle install"
sudo -u discourse -H bundle install --deployment

cd $charm_dir

juju-log "Installed/Upgraded"
