#!/bin/bash

apt-get install -qy redis-server

cat > /home/discourse/discourse/config/redis.yml <<EOF
defaults: &defaults
  host: localhost
  port: 6379
  db: 0
  cache_db: 2

production:
  <<: *defaults
EOF

juju-log "Redis is dead"

if [ -f ".psql" ]; then
  restart discourse
fi
