#!/bin/bash

set -ex

# If we have a database, which we might not, then back it up!
if [ -f ".psql" ]; then
  cd /home/discourse/discourse
  if [ -f "$CHARM_DIR/.database.yml.bak" ]; then
    cat $CHARM_DIR/.database.yml.bak > config/database.yml
  elif [ -f "config/database.yml" ] && [ ! -f "$CHARM_DIR/.database.yml.bak" ]; then
    # For backwards compatibility. Remove and favor running relation hook again when bug is fixed in juju-core
    cp config/database.yml $CHARM_DIR/.database.yml.bak
  fi

  if [ -f "$CHARM_DIR/.redis.yml.bak" ]; then
    cat $CHARM_DIR/.redis.yml.bak > config/redis.yml
  elif [ -f "$CHARM_DIR/.redis" ] && [ ! -f "$CHARM_DIR/.redis.yml.bak" ]; then
    cat > config/redis.yml <<EOF
defaults: &defaults
  host: $redis_srv
  port: 6379
  db: 0
  cache_db: 2

production:
  <<: *defaults
EOF
    cp config/redis.yml $CHARM_DIR/.redis.yml.bak
  fi
fi

cd $CHARM_DIR

# This should handle the rest!
hooks/config-changed
